name: Build

on:
  push:
    branches:
      - 'main'
  pull_request: {}
  workflow_dispatch:

jobs:
  build:
    permissions:
      # https://github.com/marketplace/actions/publish-test-results#permissions
      checks: write
      pull-requests: write

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - name: Set up JDK
        uses: actions/setup-java@03ad4de0992f5dab5e18fcb136590ce7c4a0ac95 # v5
        with:
          distribution: 'temurin'
          java-version: '21'
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v6
        with:
          node-version-file: '.nvmrc'
          registry-url: 'https://artifacts.itemis.cloud/repository/npm-open/'
          scope: '<@modelix>'
      - name: Set up pnpm
        uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
      - name: Install dependencies
        run: pnpm install
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew build -PciBuild=true -Pgpr.token=${{ secrets.GITHUB_TOKEN }} -Pmps.version.major=2023.3
      - name: Archive test report
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        if: always()
        with:
          name: test-report
          path: |
            */build/test-results
            */build/reports
      - name: Publish test results
        uses: EnricoMi/publish-unit-test-result-action@d0a4676d0e0b938bc201470d88276b7c74c712b3 # v2
        # Also report in case the build failed
        if: always()
        with:
          files: |
            **/test-results/**/*.xml
