name: MPS Compatibility

on:
  push:
    branches:
      - 'main'
  pull_request: {}
  workflow_dispatch:

jobs:
  build-mps-plugin:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version:
          # also adjust the compatibility version range of the MPS plugin
          - "2024.1"
          - "2025.1"
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - name: Set up JDK
        uses: actions/setup-java@dd06d9cba3e5552c54d9f8ea23572deb30010f7c # v5
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Use Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v6
        with:
          node-version-file: '.nvmrc'
      - name: Set up pnpm
        uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6.0.10
      - name: Install dependencies
        run: pnpm install
      - name: Build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: >-
          ./gradlew
          :projectional-editor-ssr-mps:build
          :projectional-editor-ssr-mps-languages:build
          -PciBuild=true
          -Pgpr.token=${{ secrets.GITHUB_TOKEN }}
          -Pmps.version.major=${{ matrix.version }}
      - name: Archive test report
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        if: always()
        with:
          name: test-report-${{ matrix.version }}
          path: |
            */build/test-results
            */build/reports
