name: MPS Compatibility

on:
  push:
    branches:
      - 'main'
  pull_request: {}
  workflow_dispatch:

jobs:
  build-mps-plugin:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version:
          # also adjust the compatibility version range of the MPS plugin
          - "2024.1"
          - "2025.1"
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - name: Set up JDK
        uses: actions/setup-java@1bcf9fb12cf4aa7d266a90ae39939e61372fe520 # v5
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Use Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version-file: '.nvmrc'
      - name: Set up pnpm
        uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
      - name: Install dependencies
        run: pnpm install
      - name: Build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: >-
          ./gradlew
          :projectional-editor-ssr-mps:build
          :projectional-editor-ssr-mps-languages:build
          -PciBuild=true
          -Pgpr.token=${{ secrets.GITHUB_TOKEN }}
          -Pmps.version.major=${{ matrix.version }}
      - name: Archive test report
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        if: always()
        with:
          name: test-report-${{ matrix.version }}
          path: |
            */build/test-results
            */build/reports
