name: Publish

on:
  push:
    tags:
      - '**'

jobs:
  newRelease:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18.3.0'
          registry-url: 'https://npm.pkg.github.com'
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Use tag as version
        run: echo "${GITHUB_REF#refs/*/}" > version.txt
      - name: Build and Publish
        env:
        run: ./gradlew build publish -PciBuild=true -Partifacts.itemis.cloud.user=${{secrets.ARTIFACTS_ITEMIS_CLOUD_USER}} -Partifacts.itemis.cloud.pw=${{secrets.ARTIFACTS_ITEMIS_CLOUD_PW}} -Pgpr.token=${{ secrets.GITHUB_TOKEN }}
